### ISSUE TITLE
questions about the prediction sub-network

### ISSUE THREAD

**Issue by yaoqi-zd** [huzi96/Coarse2Fine-ImaComp#3]
Hi, may I ask what's the advantages of the prediction sub-network over cascade convolutional layers in estimating the mean and std?

In your paper, you said `the hyper latent representations are densely sampled to complete the estimation, without the potential information loss during convolutional operations`.  I'm a little confused, the prediction sub-network also contains convolutional operations, so it can also cause information loss?

btw, how much performance improvements can this prediction sub-network bring?

**Comment by huzi96** [comment]
Earlier experimental results show that the subnetwork does much better in generating the mean and scale for the entropy model. This is probably because we conduct a dense sampling of the latent representation. However, more experimental and theoretical analysis is needed to fully understand what brings in the improvement.

**Comment by yaoqi-zd** [comment]
get it, thanks for your reply!
